# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfb0E8gq47WWsIsvZoUEKNUOn59yR_ap
"""

import streamlit as st
import joblib
import numpy as np

# Load the model
model = joblib.load('logistic_regression_model.pkl')

# App title
st.title('Machine Learning Model Deployment')

# Input fields
input_1 = st.number_input('Enter feature 1 value:')
input_2 = st.number_input('Enter feature 2 value:')

# Predict
if st.button('Predict'):
    features = np.array([[input_1, input_2]])
    prediction = model.predict(features)
    st.write(f'The predicted result is: {prediction}')

# ! pip install streamlit